#
# Copyright (C) 2024 The Android Open Source Project
# Copyright (C) 2024 SebaUbuntu's TWRP device tree generator
# SPDX-License-Identifier: Apache-2.0
#


DEVICE_PATH := device/amlogic/p281
BUILD_BROKEN_DUP_RULES := true
BOARD_VENDOR := amlogic
BOARD_DEVICE := p281
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
# BOARD_VNDK_VERSION := current

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_BOOTLOADER := true
TARGET_FORCE_CPU_UPLOAD := true


# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_CPU_SMP := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a9
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_CPU_ABI),$(TARGET_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_USES_64_BIT_BINDER := true
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_KERNEL_IMAGE_NAME := Image
BOARD_USES_METADATA_PARTITION := true
BOARD_ROOT_EXTRA_FOLDERS += metadata


# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := sun50iw9p1
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 160

# BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
# Kernel
BOARD_KERNEL_CMDLINE += firmware_class.path=/vendor/etc/firmware
BOARD_KERNEL_CMDLINE += selinux=0
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BOARD_KERNEL_CMDLINE += androidboot.dtbo_idx=0,1,2

BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x02f88000
BOARD_KERNEL_TAGS_OFFSET := 0xfff88100
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_SECOND_OFFSET := 0x00e88000
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_DTB_OFFSET := 0x03f88000
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_INCLUDE_DTB_IN_BOOTIMG :=
BOARD_DTB_OFFSET := 0x03f88000
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
endif

# DynamicPartitions
TARGET_USES_MKE2FS := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1483444224
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 94593024
BOARD_VENDORIMAGE_PARTITION_SIZE := 169263104
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_PRODUCT_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SUPER_PARTITION_SIZE := 2147483648
BOARD_SUPER_PARTITION_GROUPS := sb
BOARD_SB_PARTITION_LIST := system vendor product
BOARD_SB_SIZE := 2147483648

# Partition
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := sun50iw9p1
TARGET_BOARD_PLATFORM_GPU := ARM Mali-G31 MP2

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_SUPPRESS_SECURE_ERASE := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

BOARD_HAS_NO_REAL_SDCARD := false
TW_DEFAULT_EXTERNAL_STORAGE := true

# Verified Boot
BOARD_AVB_ENABLE := true

# OS
PLATFORM_SECURITY_PATCH := 2020-09-05
VENDOR_SECURITY_PATCH := 2020-09-05
PLATFORM_VERSION := 10
BOARD_OS_VERSION := 10.0.0
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_USE_FSCRYPT_POLICY := 2

# TWRP EXCLUDE
TW_EXCLUDE_APEX := true
TW_EXCLUDE_BASH := false
TW_EXCLUDE_NANO := false
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_SUPERSU := true
TW_NO_HAPTICS := true
TW_SKIP_COMPATIBILITY_CHECK := true
TW_SUPPORT_INPUT_AIDL_HAPTICS := false
TW_SUPPORT_INPUT_AIDL_HAPTICS_FIX_OFF := false

# TWRP Configuration
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := ja
TW_DEFAULT_BRIGHTNESS := 120
TW_MAX_BRIGHTNESS := 255
TW_THEME := landscape_mdpi
RECOVERY_SDCARD_ON_DATA := true
TW_NO_SCREEN_TIMEOUT := true
TW_NO_SCREEN_BLANK := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_USE_EXTERNAL_STORAGE := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_OVERRIDE_SYSTEM_PROPS := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_FASTBOOTD := true
TW_INCLUDE_RESETPROP := true
